GU_TEXTURE_SHIFT = lambda n: n<<0
GU_TEXTURE_8BIT = GU_TEXTURE_SHIFT(1)
GU_TEXTURE_16BIT = GU_TEXTURE_SHIFT(2)
GU_TEXTURE_32BITF = GU_TEXTURE_SHIFT(3)
GU_TEXTURE_BITS = GU_TEXTURE_SHIFT(3)

GU_COLOR_SHIFT = lambda n: n<<2
GU_COLOR_5650 = GU_COLOR_SHIFT(4)
GU_COLOR_5551 = GU_COLOR_SHIFT(5)
GU_COLOR_4444 = GU_COLOR_SHIFT(6)
GU_COLOR_8888 = GU_COLOR_SHIFT(7)
GU_COLOR_BITS = GU_COLOR_SHIFT(7)

GU_NORMAL_SHIFT = lambda n: n<<5
GU_NORMAL_8BIT = GU_NORMAL_SHIFT(1)
GU_NORMAL_16BIT = GU_NORMAL_SHIFT(2)
GU_NORMAL_32BITF = GU_NORMAL_SHIFT(3)
GU_NORMAL_BITS = GU_NORMAL_SHIFT(3)

GU_VERTEX_SHIFT = lambda n: n<<7
GU_VERTEX_8BIT = GU_VERTEX_SHIFT(1)
GU_VERTEX_16BIT = GU_VERTEX_SHIFT(2)
GU_VERTEX_32BITF = GU_VERTEX_SHIFT(3)
GU_VERTEX_BITS = GU_VERTEX_SHIFT(3)

GU_WEIGHT_SHIFT = lambda n: n<<9
GU_WEIGHT_8BIT = GU_WEIGHT_SHIFT(1)
GU_WEIGHT_16BIT = GU_WEIGHT_SHIFT(2)
GU_WEIGHT_32BITF = GU_WEIGHT_SHIFT(3)
GU_WEIGHT_BITS = GU_WEIGHT_SHIFT(3)

GU_INDEX_SHIFT = lambda n: n<<11
GU_INDEX_8BIT = GU_INDEX_SHIFT(1)
GU_INDEX_16BIT = GU_INDEX_SHIFT(2)
GU_INDEX_BITS = GU_INDEX_SHIFT(3)

GU_WEIGHTS = lambda n: ((((n)-1)&7)<<14)
GU_WEIGHTS_BITS = GU_WEIGHTS(8)
GU_VERTICES = lambda n: ((((n)-1)&7)<<18)
GU_VERTICES_BITS = GU_VERTICES(8)

GU_TRANSFORM_SHIFT = lambda n: ((n)<<23)
GU_TRANSFORM_3D = GU_TRANSFORM_SHIFT(0)
GU_TRANSFORM_2D = GU_TRANSFORM_SHIFT(1)
GU_TRANSFORM_BITS = GU_TRANSFORM_SHIFT(1)